# Site settings
title: Knight in Coding Armor
header-img: img/home-bg.png
email: sammay82@yahoo.com
copyright_name: sammay82
description: > # this means to ignore newlines until "baseurl:"
  Discussions, discoveries, and lamentations along my quest to learn. co
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sammay82
learn_profile: sammay82
email_username: sammay82@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
